In [1]:
import numpy as np
import sympy as sp

def latex_matrix(matrix):
    """Convert a NumPy matrix to LaTeX format using SymPy."""
    # Convert NumPy array to SymPy Matrix
    sympy_matrix = sp.Matrix(matrix)
    return sp.latex(sympy_matrix)

def convolution2d(input_matrix, kernel):
    """Perform 2D convolution and generate LaTeX for calculations."""
    input_matrix = np.array(input_matrix)
    kernel = np.array(kernel)
    kernel_size = kernel.shape[0]
    input_size = input_matrix.shape[0]

    output_size = input_size - kernel_size + 1
    output_matrix = np.zeros((output_size, output_size))

    latex_results = []
    for i in range(output_size):
        for j in range(output_size):
            # Extract the current region of the input matrix
            region = input_matrix[i:i+kernel_size, j:j+kernel_size]

            # Perform convolution
            result = np.sum(region * kernel)
            output_matrix[i, j] = result

            # LaTeX for the calculation
            region_latex = latex_matrix(region)
            kernel_latex = latex_matrix(kernel)
            calculation = f"\\begin{{align*}} \n"
            calculation += f"& {kernel_latex} \\circledast {region_latex} \\\\ \n"
            calculation += f"&= " + " + ".join(f"{kernel[i, j]} \\times {region[i, j]}" for i in range(kernel_size) for j in range(kernel_size)) + " \\\\ \n"
            calculation += f"&= {result} \n\\end{{align*}}"
            latex_results.append(calculation)

    return output_matrix, latex_results

# Define the input matrix and kernels
input_matrix = [
    [2, 2, 2, 2, 2],
    [3, 3, 3, 3, 3],
    [1, 1, 1, 1, 1],
    [3, 3, 3, 3, 3],
    [2, 2, 2, 2, 2]
]

kernel1 = [
    [-1, -1, -1],
    [2, 2, 2],
    [-1, -1, -1]
]

kernel2 = [
    [-1, 2, -1],
    [-1, 2, -1],
    [-1, 2, -1]
]

# Perform convolution and generate LaTeX
output1, latex1 = convolution2d(input_matrix, kernel1)
output2, latex2 = convolution2d(input_matrix, kernel2)

# Print results
print("Output matrix for kernel W1:")
print(output1)
print("\nLaTeX Calculations for kernel W1:")
for latex in latex1:
    print(latex)

print("\nOutput matrix for kernel W2:")
print(output2)
print("\nLaTeX Calculations for kernel W2:")
for latex in latex2:
    print(latex)


Output matrix for kernel W1:
[[  9.   9.   9.]
 [-12. -12. -12.]
 [  9.   9.   9.]]

LaTeX Calculations for kernel W1:
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 2 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 1 + -1 \times 1 + -1 \times 1 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 2 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 1 + -1 \times 1 + -1 \times 1 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 

Output matrix for kernel W1:
[[  9.   9.   9.]
 [-12. -12. -12.]
 [  9.   9.   9.]]

LaTeX Calculations for kernel W1:
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 2 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 1 + -1 \times 1 + -1 \times 1 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 2 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 1 + -1 \times 1 + -1 \times 1 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 2 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 1 + -1 \times 1 + -1 \times 1 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 3 + 2 \times 1 + 2 \times 1 + 2 \times 1 + -1 \times 3 + -1 \times 3 + -1 \times 3 \\ 
&= -12 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 3 + 2 \times 1 + 2 \times 1 + 2 \times 1 + -1 \times 3 + -1 \times 3 + -1 \times 3 \\ 
&= -12 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 3 + 2 \times 1 + 2 \times 1 + 2 \times 1 + -1 \times 3 + -1 \times 3 + -1 \times 3 \\ 
&= -12 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + -1 \times 1 + -1 \times 1 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 2 + -1 \times 2 + -1 \times 2 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + -1 \times 1 + -1 \times 1 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 2 + -1 \times 2 + -1 \times 2 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + -1 \times 1 + -1 \times 1 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 2 + -1 \times 2 + -1 \times 2 \\ 
&= 9 
\end{align*}

Output matrix for kernel W2:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

LaTeX Calculations for kernel W2:
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 2 + 2 \times 2 + -1 \times 2 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 2 + 2 \times 2 + -1 \times 2 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 2 + 2 \times 2 + -1 \times 2 \\ 
&= 0 
\end{align*}


# Full equation of a network with any structure so i can have the Latex code: Without bias

In [2]:
def generate_network_latex(structure):
    input_size = structure[0]
    hidden_size = structure[1]
    output_size = structure[2]

    # Generate weight matrices
    weights_input_hidden = [f"w_{i+1}" for i in range(input_size * hidden_size)]
    weights_hidden_output = [f"w_{i+1}" for i in range(input_size * hidden_size, input_size * hidden_size + hidden_size * output_size)]

    # Generate variable matrices
    x_vars = [f"x_{i+1}" for i in range(input_size)]
    n_hidden_vars = [f"n_{i+1}" for i in range(hidden_size)]
    n_output_vars = [f"n_{i+1}" for i in range(hidden_size, hidden_size + output_size)]

    # Generate LaTeX strings
    win_latex = f"\\begin{{pmatrix}} " + " & ".join([f"w_{i+1}" for i in range(hidden_size)]) + " \\end{pmatrix} "
    whid_latex = f"\\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} "
    x_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} "
    nhid_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} "
    nout_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_output_vars) + " \\end{pmatrix} "

    # Generate activation function LaTeX
    nhid_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join([f"w_{i+1}" for i in range(input_size)]) + " \\end{pmatrix} \\cdot \\begin{pmatrix} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} \\right) = \\begin{pmatrix} " + " \\\\ ".join([f"\\sigma(" + " + ".join([f"w_{i+1}x_{i+1}" for i in range(input_size)]) + ")" for i in range(hidden_size)]) + " \\end{pmatrix} "
    nout_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} \\cdot \\begin{pmatrix} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} \\right) = \\sigma \\left( " + " + ".join([f"w_{i+1}n_{i+1}" for i in range(hidden_size)]) + " \\right) "
    act_eq = f"act = \\sigma \\left( " + " + ".join([f"w_{i+1}n_{i+1}" for i in range(hidden_size)]) + " \\right) "

    # Count total weights
    total_weights = len(weights_input_hidden) + len(weights_hidden_output)

    # Print results with $$ to ensure LaTeX formatting
    print(f"$$")
    print(f"Win = {win_latex} $$")
    print(f"$$")
    print(f"whid = {whid_latex} $$")
    print(f"$$")
    print(f"x = {x_latex} $$")
    print(f"$$")
    print(f"nhid = {nhid_latex} $$")
    print(f"$$")
    print(f"nout = {nout_latex} $$")
    print(f"$$")
    print(f"nhid = \\sigma(Win \\cdot x) = {nhid_eq} $$")
    print(f"$$")
    print(f"nout = \\sigma(whid \\cdot nhid) = {nout_eq} $$")
    print(f"$$")
    print(f"act = {act_eq} $$")
    print(f"$$")
    print(f"The network has {total_weights} weights.")
    print(f"$$")

# Example usage for structure [2, 4, 1]
structure = [2, 4, 1]
generate_network_latex(structure)


$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x) = \sigma \left( \begin{pmatrix} w_1 & w_2 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} \right) = \begin{pmatrix} \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_1x_1 + w_2x_2) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} \right) = \sigma \left( w_1n_1 + w_2n_2 + w_3n_3 + w_4n_4 \right)  $$
$$
act = act = \sigma \left( w_1n_1 + w_2n_2 + w_3n_3 + w_4n_4 \right)  $$
$$
The network has 12 weights.
$$


$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x) = \sigma \left( \begin{pmatrix} w_1 & w_2 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} \right) = \begin{pmatrix} \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_1x_1 + w_2x_2) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} \right) = \sigma \left( w_1n_1 + w_2n_2 + w_3n_3 + w_4n_4 \right)  $$
$$
act = act = \sigma \left( w_1n_1 + w_2n_2 + w_3n_3 + w_4n_4 \right)  $$

The network has 12 weights.



# Full equation of a network with any structure so i can have the Latex code: with bias

In [11]:
def generate_network_latex_with_recurrent(structure):
    input_size = structure[0]
    hidden_size = structure[1]
    output_size = structure[2]

    # Generate weight matrices
    weights_input_hidden = [f"w_{i+1}" for i in range(input_size * hidden_size)]
    weights_hidden_output = [f"w_{i+1}" for i in range(input_size * hidden_size, input_size * hidden_size + hidden_size * output_size)]

    # Generate variable matrices
    x_vars = [f"x_{i+1}" for i in range(input_size)]
    n_hidden_vars = [f"n_{i+1}" for i in range(hidden_size)]
    n_output_vars = [f"n_{i+1}" for i in range(hidden_size, hidden_size + output_size)]

    # Generate bias terms
    biases_hidden = [f"b_{i+1}" for i in range(hidden_size)]
    biases_output = [f"b_{i+1+hidden_size}" for i in range(output_size)]

    # Generate LaTeX strings
    win_latex = f"\\begin{{pmatrix}} " + " & ".join(weights_input_hidden) + " \\end{pmatrix} "
    whid_latex = f"\\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} "
    x_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} "
    nhid_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} "
    nout_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_output_vars) + " \\end{pmatrix} "

    # Add biases
    bias_hidden_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(biases_hidden) + " \\end{pmatrix} "
    bias_output_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(biases_output) + " \\end{pmatrix} "

    # Generate activation function LaTeX
    nhid_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join(weights_input_hidden) + " \\end{pmatrix} \\cdot \\begin{pmatrix} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} + \\begin{pmatrix} " + " \\\\ ".join(biases_hidden) + " \\end{pmatrix} \\right) = \\begin{pmatrix} " + " \\\\ ".join([f"\\sigma(w_{i+1}x_{i+1} + b_{i+1})" for i in range(hidden_size)]) + " \\end{pmatrix} "
    nout_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} \\cdot \\begin{pmatrix} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} + \\begin{pmatrix} " + " \\\\ ".join(biases_output) + " \\end{pmatrix} \\right) = \\sigma \\left( " + " + ".join([f"w_{i+1}\\sigma(w_{i+1}x_{i+1} + b_{i+1})" for i in range(hidden_size)]) + " \\right) "
    act_eq = f"act = \\sigma \\left( " + " + ".join([f"w_{i+1}\\sigma(w_{i+1}x_{i+1} + b_{i+1})" for i in range(hidden_size)]) + " \\right) "

    # Count total weights
    total_feed_forward_weights = len(weights_input_hidden) + len(weights_hidden_output)
    total_recurrent_weights = hidden_size  # One recurrent connection per hidden neuron
    total_biases = len(biases_hidden) + len(biases_output)
    total_weights = total_feed_forward_weights + total_recurrent_weights + total_biases

    # Print results with $$ to ensure LaTeX formatting
    print(f"$$")
    print(f"Win = {win_latex} $$")
    print(f"$$")
    print(f"whid = {whid_latex} $$")
    print(f"$$")
    print(f"x = {x_latex} $$")
    print(f"$$")
    print(f"nhid = {nhid_latex} $$")
    print(f"$$")
    print(f"nout = {nout_latex} $$")
    print(f"$$")
    print(f"nhid = \\sigma(Win \\cdot x + \\text{{biases}}) = {nhid_eq} $$")
    print(f"$$")
    print(f"nout = \\sigma(whid \\cdot nhid + \\text{{biases}}) = {nout_eq} $$")
    print(f"$$")
    print(f"act = {act_eq} $$")
    print(f"$$")
    print(f"The Feed-Forward Weights: {total_feed_forward_weights} weights.")
    print(f"The Recurrent Connections: {total_recurrent_weights} weights.")
    print(f"Total Biases: {total_biases} weights.")
    print(f"Now, The network has {total_weights} weights.")
    print(f"$$")

# Example usage for structure [2, 4, 1] with biases and recurrent connections
structure = [2, 4, 1]
generate_network_latex_with_recurrent(structure)

$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x + \text{biases}) = \sigma \left( \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} + \begin{pmatrix} b_1 \\ b_2 \\ b_3 \\ b_4 \end{pmatrix} \right) = \begin{pmatrix} \sigma(w_1x_1 + b_1) \\ \sigma(w_2x_2 + b_2) \\ \sigma(w_3x_3 + b_3) \\ \sigma(w_4x_4 + b_4) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid + \text{biases}) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} + \begin{pmatrix} b_5 \end{pmatrix} \right) = \sigma \left( w_1\sigma(w_1x_1 + b_1) + w_2\sigma(w_2x_2 + b_2) + 

$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x + \text{biases}) = \sigma \left( \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} + \begin{pmatrix} b_1 \\ b_2 \\ b_3 \\ b_4 \end{pmatrix} \right) = \begin{pmatrix} \sigma(w_1x_1 + b_1) \\ \sigma(w_2x_2 + b_2) \\ \sigma(w_3x_3 + b_3) \\ \sigma(w_4x_4 + b_4) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid + \text{biases}) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} + \begin{pmatrix} b_5 \end{pmatrix} \right) = \sigma \left( w_1\sigma(w_1x_1 + b_1) + w_2\sigma(w_2x_2 + b_2) + w_3\sigma(w_3x_3 + b_3) + w_4\sigma(w_4x_4 + b_4) \right)  $$
$$
act = act = \sigma \left( w_1\sigma(w_1x_1 + b_1) + w_2\sigma(w_2x_2 + b_2) + w_3\sigma(w_3x_3 + b_3) + w_4\sigma(w_4x_4 + b_4) \right)  $$

**The Feed-Forward Weights**: 12 weights.
**The Recurrent Connections**: 4 weights.
**Total Biases**: 5 weights.
**Now, The network has** 21 weights.



# Second methodology 

In [14]:
def generate_network_latex_with_recurrent(structure):
    input_size = structure[0]
    hidden_size = structure[1]
    output_size = structure[2]

    # Generate weight matrices
    weights_input_hidden = [f"w_{i+1}" for i in range(input_size * hidden_size)]
    weights_hidden_output = [f"w_{i+1}" for i in range(input_size * hidden_size, input_size * hidden_size + hidden_size * output_size)]

    # Generate variable matrices
    x_vars = [f"x_{i+1}" for i in range(input_size)]
    n_hidden_vars = [f"n_{i+1}" for i in range(hidden_size)]
    n_output_vars = [f"n_{i+1}" for i in range(hidden_size, hidden_size + output_size)]

    # Generate bias terms
    biases_hidden = [f"b_{i+1}" for i in range(hidden_size)]
    biases_output = [f"b_{i+1+hidden_size}" for i in range(output_size)]

    # Generate LaTeX strings
    win_latex = f"\\begin{{pmatrix}} " + " & ".join(weights_input_hidden) + " \\end{pmatrix} "
    whid_latex = f"\\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} "
    x_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} "
    nhid_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} "
    nout_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_output_vars) + " \\end{pmatrix} "

    # Add biases
    bias_hidden_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(biases_hidden) + " \\end{pmatrix} "
    bias_output_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(biases_output) + " \\end{pmatrix} "

    # Generate activation function LaTeX
    nhid_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join(weights_input_hidden) + " \\end{pmatrix} \\cdot \\begin{pmatrix} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} + \\begin{pmatrix} " + " \\\\ ".join(biases_hidden) + " \\end{pmatrix} \\right) = \\begin{pmatrix} " + " \\\\ ".join([f"\\sigma(w_{i+1}x_{i+1} + b_{i+1})" for i in range(hidden_size)]) + " \\end{pmatrix} "
    nout_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} \\cdot \\begin{pmatrix} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} + \\begin{pmatrix} " + " \\\\ ".join(biases_output) + " \\end{pmatrix} \\right) = \\sigma \\left( " + " + ".join([f"w_{i+1}\\sigma(w_{i+1}x_{i+1} + b_{i+1})" for i in range(hidden_size)]) + " \\right) "
    act_eq = f"act = \\sigma \\left( " + " + ".join([f"w_{i+1}\\sigma(w_{i+1}x_{i+1} + b_{i+1})" for i in range(hidden_size)]) + " \\right) "

    # Count total weights
    total_feed_forward_weights = len(weights_input_hidden) + len(weights_hidden_output)
    total_recurrent_weights = hidden_size * hidden_size  # Fully connected recurrent connections in hidden layer
    total_biases = len(biases_hidden) + len(biases_output)
    total_weights = total_feed_forward_weights + total_recurrent_weights + total_biases

    # Print results with $$ to ensure LaTeX formatting
    print(f"$$")
    print(f"Win = {win_latex} $$")
    print(f"$$")
    print(f"whid = {whid_latex} $$")
    print(f"$$")
    print(f"x = {x_latex} $$")
    print(f"$$")
    print(f"nhid = {nhid_latex} $$")
    print(f"$$")
    print(f"nout = {nout_latex} $$")
    print(f"$$")
    print(f"nhid = \\sigma(Win \\cdot x + \\text{{biases}}) = {nhid_eq} $$")
    print(f"$$")
    print(f"nout = \\sigma(whid \\cdot nhid + \\text{{biases}}) = {nout_eq} $$")
    print(f"$$")
    print(f"act = {act_eq} $$")
    print(f"$$")
    print(f"The Feed-Forward Weights: {total_feed_forward_weights} weights.")
    print(f"The Recurrent Connections: {total_recurrent_weights} weights.")
    print(f"Total Biases: {total_biases} weights.")
    print(f"Now, The network has {total_weights} weights.")
    print(f"$$")

# Example usage for structure [2, 4, 1] with biases and recurrent connections
structure = [2, 4, 1]
generate_network_latex_with_recurrent(structure)

$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x + \text{biases}) = \sigma \left( \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} + \begin{pmatrix} b_1 \\ b_2 \\ b_3 \\ b_4 \end{pmatrix} \right) = \begin{pmatrix} \sigma(w_1x_1 + b_1) \\ \sigma(w_2x_2 + b_2) \\ \sigma(w_3x_3 + b_3) \\ \sigma(w_4x_4 + b_4) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid + \text{biases}) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} + \begin{pmatrix} b_5 \end{pmatrix} \right) = \sigma \left( w_1\sigma(w_1x_1 + b_1) + w_2\sigma(w_2x_2 + b_2) + 

$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x + \text{biases}) = \sigma \left( \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} + \begin{pmatrix} b_1 \\ b_2 \\ b_3 \\ b_4 \end{pmatrix} \right) = \begin{pmatrix} \sigma(w_1x_1 + b_1) \\ \sigma(w_2x_2 + b_2) \\ \sigma(w_3x_3 + b_3) \\ \sigma(w_4x_4 + b_4) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid + \text{biases}) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} + \begin{pmatrix} b_5 \end{pmatrix} \right) = \sigma \left( w_1\sigma(w_1x_1 + b_1) + w_2\sigma(w_2x_2 + b_2) + w_3\sigma(w_3x_3 + b_3) + w_4\sigma(w_4x_4 + b_4) \right)  $$
$$
act = act = \sigma \left( w_1\sigma(w_1x_1 + b_1) + w_2\sigma(w_2x_2 + b_2) + w_3\sigma(w_3x_3 + b_3) + w_4\sigma(w_4x_4 + b_4) \right)  $$

**The Feed-Forward Weights**: 12 weights.
**The Recurrent Connections**: 16 weights.
**Total Biases**: 5 weights.
**Now, The network has 33 weights.**

