# MaxPooling assuming no padding

In [1]:
import numpy as np
import sympy as sp

def latex_matrix(matrix):
    """Convert a NumPy matrix to LaTeX format using SymPy."""
    # Convert NumPy array to SymPy Matrix
    sympy_matrix = sp.Matrix(matrix)
    return sp.latex(sympy_matrix)

def convolution2d(input_matrix, kernel):
    """Perform 2D convolution and generate LaTeX for calculations."""
    input_matrix = np.array(input_matrix)
    kernel = np.array(kernel)
    kernel_size = kernel.shape[0]
    input_size = input_matrix.shape[0]

    output_size = input_size - kernel_size + 1
    output_matrix = np.zeros((output_size, output_size))

    latex_results = []
    for i in range(output_size):
        for j in range(output_size):
            # Extract the current region of the input matrix
            region = input_matrix[i:i+kernel_size, j:j+kernel_size]

            # Perform convolution
            result = np.sum(region * kernel)
            output_matrix[i, j] = result

            # LaTeX for the calculation
            region_latex = latex_matrix(region)
            kernel_latex = latex_matrix(kernel)
            calculation = f"\\begin{{align*}} \n"
            calculation += f"& {kernel_latex} \\circledast {region_latex} \\\\ \n"
            calculation += f"&= " + " + ".join(f"{kernel[i, j]} \\times {region[i, j]}" for i in range(kernel_size) for j in range(kernel_size)) + " \\\\ \n"
            calculation += f"&= {result} \n\\end{{align*}}"
            latex_results.append(calculation)

    return output_matrix, latex_results

# Define the input matrix and kernels
input_matrix = [
    [2, 2, 2, 2, 2],
    [3, 3, 3, 3, 3],
    [1, 1, 1, 1, 1],
    [3, 3, 3, 3, 3],
    [2, 2, 2, 2, 2]
]

kernel1 = [
    [-1, -1, -1],
    [2, 2, 2],
    [-1, -1, -1]
]

kernel2 = [
    [-1, 2, -1],
    [-1, 2, -1],
    [-1, 2, -1]
]

# Perform convolution and generate LaTeX
output1, latex1 = convolution2d(input_matrix, kernel1)
output2, latex2 = convolution2d(input_matrix, kernel2)

# Print results
print("Output matrix for kernel W1:")
print(output1)
print("\nLaTeX Calculations for kernel W1:")
for latex in latex1:
    print(latex)

print("\nOutput matrix for kernel W2:")
print(output2)
print("\nLaTeX Calculations for kernel W2:")
for latex in latex2:
    print(latex)


Output matrix for kernel W1:
[[  9.   9.   9.]
 [-12. -12. -12.]
 [  9.   9.   9.]]

LaTeX Calculations for kernel W1:
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 2 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 1 + -1 \times 1 + -1 \times 1 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 2 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 1 + -1 \times 1 + -1 \times 1 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 

Output matrix for kernel W1:
[[  9.   9.   9.]
 [-12. -12. -12.]
 [  9.   9.   9.]]

LaTeX Calculations for kernel W1:
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 2 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 1 + -1 \times 1 + -1 \times 1 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 2 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 1 + -1 \times 1 + -1 \times 1 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 2 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 1 + -1 \times 1 + -1 \times 1 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 3 + 2 \times 1 + 2 \times 1 + 2 \times 1 + -1 \times 3 + -1 \times 3 + -1 \times 3 \\ 
&= -12 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 3 + 2 \times 1 + 2 \times 1 + 2 \times 1 + -1 \times 3 + -1 \times 3 + -1 \times 3 \\ 
&= -12 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 3 + 2 \times 1 + 2 \times 1 + 2 \times 1 + -1 \times 3 + -1 \times 3 + -1 \times 3 \\ 
&= -12 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + -1 \times 1 + -1 \times 1 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 2 + -1 \times 2 + -1 \times 2 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + -1 \times 1 + -1 \times 1 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 2 + -1 \times 2 + -1 \times 2 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + -1 \times 1 + -1 \times 1 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 2 + -1 \times 2 + -1 \times 2 \\ 
&= 9 
\end{align*}

Output matrix for kernel W2:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

LaTeX Calculations for kernel W2:
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 2 + 2 \times 2 + -1 \times 2 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 2 + 2 \times 2 + -1 \times 2 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 2 + 2 \times 2 + -1 \times 2 \\ 
&= 0 
\end{align*}


# assuming a padinng 

In [4]:
import numpy as np
import sympy as sp

def latex_matrix(matrix):
    """Convert a NumPy matrix to LaTeX format using SymPy."""
    # Convert NumPy array to SymPy Matrix
    sympy_matrix = sp.Matrix(matrix)
    return sp.latex(sympy_matrix)

def convolution2d(input_matrix, kernel, padding=0):
    """Perform 2D convolution with optional padding and generate LaTeX for calculations."""
    input_matrix = np.array(input_matrix)
    kernel = np.array(kernel)
    kernel_size = kernel.shape[0]
    input_size = input_matrix.shape[0]

    # Apply padding to the input matrix
    if padding > 0:
        input_matrix = np.pad(input_matrix, pad_width=padding, mode='constant', constant_values=0)
        input_size = input_matrix.shape[0]

    output_size = input_size - kernel_size + 1
    output_matrix = np.zeros((output_size, output_size))

    latex_results = []
    for i in range(output_size):
        for j in range(output_size):
            # Extract the current region of the input matrix
            region = input_matrix[i:i+kernel_size, j:j+kernel_size]

            # Perform convolution
            result = np.sum(region * kernel)
            output_matrix[i, j] = result

            # LaTeX for the calculation
            region_latex = latex_matrix(region)
            kernel_latex = latex_matrix(kernel)
            calculation = f"\\begin{{align*}} \n"
            calculation += f"& {kernel_latex} \\circledast {region_latex} \\\\ \n"
            calculation += f"&= " + " + ".join(f"{kernel[i, j]} \\times {region[i, j]}" for i in range(kernel_size) for j in range(kernel_size)) + " \\\\ \n"
            calculation += f"&= {result} \n\\end{{align*}}"
            latex_results.append(calculation)

    return output_matrix, latex_results

# Define the input matrix and kernels
input_matrix = [
    [2, 2, 2, 2, 2],
    [3, 3, 3, 3, 3],
    [1, 1, 1, 1, 1],
    [3, 3, 3, 3, 3],
    [2, 2, 2, 2, 2]
]

kernel1 = [
    [-1, -1, -1],
    [2, 2, 2],
    [-1, -1, -1]
]

kernel2 = [
    [-1, 2, -1],
    [-1, 2, -1],
    [-1, 2, -1]
]

# Padding of 1 for "same padding"
padding = 1

# Perform convolution with padding and generate LaTeX
output1, latex1 = convolution2d(input_matrix, kernel1, padding)
output2, latex2 = convolution2d(input_matrix, kernel2, padding)

# Print results
print("Output matrix for kernel W1 with padding:")
print(output1)
print("\nLaTeX Calculations for kernel W1 with padding:")
for latex in latex1:
    print(latex)

print("\nOutput matrix for kernel W2 with padding:")
print(output2)
print("\nLaTeX Calculations for kernel W2 with padding:")
for latex in latex2:
    print(latex)


Output matrix for kernel W1 with padding:
[[  2.   3.   3.   3.   2.]
 [  6.   9.   9.   9.   6.]
 [ -8. -12. -12. -12.  -8.]
 [  6.   9.   9.   9.   6.]
 [  2.   3.   3.   3.   2.]]

LaTeX Calculations for kernel W1 with padding:
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 0 & 0\\0 & 2 & 2\\0 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 0 + -1 \times 0 + -1 \times 0 + 2 \times 0 + 2 \times 2 + 2 \times 2 + -1 \times 0 + -1 \times 3 + -1 \times 3 \\ 
&= 2 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 0 & 0\\2 & 2 & 2\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 0 + -1 \times 0 + -1 \times 0 + 2 \times 2 + 2 \times 2 + 2 \times 2 + -1 \times 3 + -1 \times 3 + -1 \times 3 \\ 
&= 3 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \lef

Output matrix for kernel W1 with padding:
[[  2.   3.   3.   3.   2.]
 [  6.   9.   9.   9.   6.]
 [ -8. -12. -12. -12.  -8.]
 [  6.   9.   9.   9.   6.]
 [  2.   3.   3.   3.   2.]]

LaTeX Calculations for kernel W1 with padding:
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 0 & 0\\0 & 2 & 2\\0 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 0 + -1 \times 0 + -1 \times 0 + 2 \times 0 + 2 \times 2 + 2 \times 2 + -1 \times 0 + -1 \times 3 + -1 \times 3 \\ 
&= 2 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 0 & 0\\2 & 2 & 2\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 0 + -1 \times 0 + -1 \times 0 + 2 \times 2 + 2 \times 2 + 2 \times 2 + -1 \times 3 + -1 \times 3 + -1 \times 3 \\ 
&= 3 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 0 & 0\\2 & 2 & 2\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 0 + -1 \times 0 + -1 \times 0 + 2 \times 2 + 2 \times 2 + 2 \times 2 + -1 \times 3 + -1 \times 3 + -1 \times 3 \\ 
&= 3 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 0 & 0\\2 & 2 & 2\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 0 + -1 \times 0 + -1 \times 0 + 2 \times 2 + 2 \times 2 + 2 \times 2 + -1 \times 3 + -1 \times 3 + -1 \times 3 \\ 
&= 3 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 0 & 0\\2 & 2 & 0\\3 & 3 & 0\end{matrix}\right] \\ 
&= -1 \times 0 + -1 \times 0 + -1 \times 0 + 2 \times 2 + 2 \times 2 + 2 \times 0 + -1 \times 3 + -1 \times 3 + -1 \times 0 \\ 
&= 2 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 2 & 2\\0 & 3 & 3\\0 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 0 + -1 \times 2 + -1 \times 2 + 2 \times 0 + 2 \times 3 + 2 \times 3 + -1 \times 0 + -1 \times 1 + -1 \times 1 \\ 
&= 6 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 2 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 1 + -1 \times 1 + -1 \times 1 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 2 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 1 + -1 \times 1 + -1 \times 1 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 2 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 1 + -1 \times 1 + -1 \times 1 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 0\\3 & 3 & 0\\1 & 1 & 0\end{matrix}\right] \\ 
&= -1 \times 2 + -1 \times 2 + -1 \times 0 + 2 \times 3 + 2 \times 3 + 2 \times 0 + -1 \times 1 + -1 \times 1 + -1 \times 0 \\ 
&= 6 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 3 & 3\\0 & 1 & 1\\0 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 0 + -1 \times 3 + -1 \times 3 + 2 \times 0 + 2 \times 1 + 2 \times 1 + -1 \times 0 + -1 \times 3 + -1 \times 3 \\ 
&= -8 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 3 + 2 \times 1 + 2 \times 1 + 2 \times 1 + -1 \times 3 + -1 \times 3 + -1 \times 3 \\ 
&= -12 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 3 + 2 \times 1 + 2 \times 1 + 2 \times 1 + -1 \times 3 + -1 \times 3 + -1 \times 3 \\ 
&= -12 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 3 + 2 \times 1 + 2 \times 1 + 2 \times 1 + -1 \times 3 + -1 \times 3 + -1 \times 3 \\ 
&= -12 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 0\\1 & 1 & 0\\3 & 3 & 0\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 0 + 2 \times 1 + 2 \times 1 + 2 \times 0 + -1 \times 3 + -1 \times 3 + -1 \times 0 \\ 
&= -8 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 1 & 1\\0 & 3 & 3\\0 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 0 + -1 \times 1 + -1 \times 1 + 2 \times 0 + 2 \times 3 + 2 \times 3 + -1 \times 0 + -1 \times 2 + -1 \times 2 \\ 
&= 6 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + -1 \times 1 + -1 \times 1 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 2 + -1 \times 2 + -1 \times 2 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + -1 \times 1 + -1 \times 1 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 2 + -1 \times 2 + -1 \times 2 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + -1 \times 1 + -1 \times 1 + 2 \times 3 + 2 \times 3 + 2 \times 3 + -1 \times 2 + -1 \times 2 + -1 \times 2 \\ 
&= 9 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 0\\3 & 3 & 0\\2 & 2 & 0\end{matrix}\right] \\ 
&= -1 \times 1 + -1 \times 1 + -1 \times 0 + 2 \times 3 + 2 \times 3 + 2 \times 0 + -1 \times 2 + -1 \times 2 + -1 \times 0 \\ 
&= 6 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 3 & 3\\0 & 2 & 2\\0 & 0 & 0\end{matrix}\right] \\ 
&= -1 \times 0 + -1 \times 3 + -1 \times 3 + 2 \times 0 + 2 \times 2 + 2 \times 2 + -1 \times 0 + -1 \times 0 + -1 \times 0 \\ 
&= 2 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\2 & 2 & 2\\0 & 0 & 0\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 3 + 2 \times 2 + 2 \times 2 + 2 \times 2 + -1 \times 0 + -1 \times 0 + -1 \times 0 \\ 
&= 3 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\2 & 2 & 2\\0 & 0 & 0\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 3 + 2 \times 2 + 2 \times 2 + 2 \times 2 + -1 \times 0 + -1 \times 0 + -1 \times 0 \\ 
&= 3 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\2 & 2 & 2\\0 & 0 & 0\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 3 + 2 \times 2 + 2 \times 2 + 2 \times 2 + -1 \times 0 + -1 \times 0 + -1 \times 0 \\ 
&= 3 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & -1 & -1\\2 & 2 & 2\\-1 & -1 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 0\\2 & 2 & 0\\0 & 0 & 0\end{matrix}\right] \\ 
&= -1 \times 3 + -1 \times 3 + -1 \times 0 + 2 \times 2 + 2 \times 2 + 2 \times 0 + -1 \times 0 + -1 \times 0 + -1 \times 0 \\ 
&= 2 
\end{align*}

Output matrix for kernel W2 with padding:
[[5. 0. 0. 0. 5.]
 [6. 0. 0. 0. 6.]
 [7. 0. 0. 0. 7.]
 [6. 0. 0. 0. 6.]
 [5. 0. 0. 0. 5.]]

LaTeX Calculations for kernel W2 with padding:
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 0 & 0\\0 & 2 & 2\\0 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 0 + 2 \times 0 + -1 \times 0 + -1 \times 0 + 2 \times 2 + -1 \times 2 + -1 \times 0 + 2 \times 3 + -1 \times 3 \\ 
&= 5 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 0 & 0\\2 & 2 & 2\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 0 + 2 \times 0 + -1 \times 0 + -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 3 + 2 \times 3 + -1 \times 3 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 0 & 0\\2 & 2 & 2\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 0 + 2 \times 0 + -1 \times 0 + -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 3 + 2 \times 3 + -1 \times 3 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 0 & 0\\2 & 2 & 2\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 0 + 2 \times 0 + -1 \times 0 + -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 3 + 2 \times 3 + -1 \times 3 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 0 & 0\\2 & 2 & 0\\3 & 3 & 0\end{matrix}\right] \\ 
&= -1 \times 0 + 2 \times 0 + -1 \times 0 + -1 \times 2 + 2 \times 2 + -1 \times 0 + -1 \times 3 + 2 \times 3 + -1 \times 0 \\ 
&= 5 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 2 & 2\\0 & 3 & 3\\0 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 0 + 2 \times 2 + -1 \times 2 + -1 \times 0 + 2 \times 3 + -1 \times 3 + -1 \times 0 + 2 \times 1 + -1 \times 1 \\ 
&= 6 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 2\\3 & 3 & 3\\1 & 1 & 1\end{matrix}\right] \\ 
&= -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}2 & 2 & 0\\3 & 3 & 0\\1 & 1 & 0\end{matrix}\right] \\ 
&= -1 \times 2 + 2 \times 2 + -1 \times 0 + -1 \times 3 + 2 \times 3 + -1 \times 0 + -1 \times 1 + 2 \times 1 + -1 \times 0 \\ 
&= 6 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 3 & 3\\0 & 1 & 1\\0 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 0 + 2 \times 3 + -1 \times 3 + -1 \times 0 + 2 \times 1 + -1 \times 1 + -1 \times 0 + 2 \times 3 + -1 \times 3 \\ 
&= 7 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\1 & 1 & 1\\3 & 3 & 3\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 0\\1 & 1 & 0\\3 & 3 & 0\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 0 + -1 \times 1 + 2 \times 1 + -1 \times 0 + -1 \times 3 + 2 \times 3 + -1 \times 0 \\ 
&= 7 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 1 & 1\\0 & 3 & 3\\0 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 0 + 2 \times 1 + -1 \times 1 + -1 \times 0 + 2 \times 3 + -1 \times 3 + -1 \times 0 + 2 \times 2 + -1 \times 2 \\ 
&= 6 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 2 + 2 \times 2 + -1 \times 2 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 2 + 2 \times 2 + -1 \times 2 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 1\\3 & 3 & 3\\2 & 2 & 2\end{matrix}\right] \\ 
&= -1 \times 1 + 2 \times 1 + -1 \times 1 + -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 2 + 2 \times 2 + -1 \times 2 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}1 & 1 & 0\\3 & 3 & 0\\2 & 2 & 0\end{matrix}\right] \\ 
&= -1 \times 1 + 2 \times 1 + -1 \times 0 + -1 \times 3 + 2 \times 3 + -1 \times 0 + -1 \times 2 + 2 \times 2 + -1 \times 0 \\ 
&= 6 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}0 & 3 & 3\\0 & 2 & 2\\0 & 0 & 0\end{matrix}\right] \\ 
&= -1 \times 0 + 2 \times 3 + -1 \times 3 + -1 \times 0 + 2 \times 2 + -1 \times 2 + -1 \times 0 + 2 \times 0 + -1 \times 0 \\ 
&= 5 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\2 & 2 & 2\\0 & 0 & 0\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 0 + 2 \times 0 + -1 \times 0 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\2 & 2 & 2\\0 & 0 & 0\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 0 + 2 \times 0 + -1 \times 0 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 3\\2 & 2 & 2\\0 & 0 & 0\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 3 + -1 \times 2 + 2 \times 2 + -1 \times 2 + -1 \times 0 + 2 \times 0 + -1 \times 0 \\ 
&= 0 
\end{align*}
\begin{align*} 
& \left[\begin{matrix}-1 & 2 & -1\\-1 & 2 & -1\\-1 & 2 & -1\end{matrix}\right] \circledast \left[\begin{matrix}3 & 3 & 0\\2 & 2 & 0\\0 & 0 & 0\end{matrix}\right] \\ 
&= -1 \times 3 + 2 \times 3 + -1 \times 0 + -1 \times 2 + 2 \times 2 + -1 \times 0 + -1 \times 0 + 2 \times 0 + -1 \times 0 \\ 
&= 5 
\end{align*}


# Full equation of a network with any structure so i can have the Latex code: Without bias

In [1]:
def generate_network_latex(structure):
    input_size = structure[0]
    hidden_size = structure[1]
    output_size = structure[2]

    # Generate weight matrices
    weights_input_hidden = [f"w_{i+1}" for i in range(input_size * hidden_size)]
    weights_hidden_output = [f"w_{i+1}" for i in range(input_size * hidden_size, input_size * hidden_size + hidden_size * output_size)]

    # Generate variable matrices
    x_vars = [f"x_{i+1}" for i in range(input_size)]
    n_hidden_vars = [f"n_{i+1}" for i in range(hidden_size)]
    n_output_vars = [f"n_{i+1}" for i in range(hidden_size, hidden_size + output_size)]

    # Generate LaTeX strings
    win_latex = f"\\begin{{pmatrix}} " + " & ".join([f"w_{i+1}" for i in range(hidden_size)]) + " \\end{pmatrix} "
    whid_latex = f"\\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} "
    x_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} "
    nhid_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} "
    nout_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_output_vars) + " \\end{pmatrix} "

    # Generate activation function LaTeX
    nhid_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join([f"w_{i+1}" for i in range(input_size)]) + " \\end{pmatrix} \\cdot \\begin{pmatrix} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} \\right) = \\begin{pmatrix} " + " \\\\ ".join([f"\\sigma(" + " + ".join([f"w_{i+1}x_{i+1}" for i in range(input_size)]) + ")" for i in range(hidden_size)]) + " \\end{pmatrix} "
    nout_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} \\cdot \\begin{pmatrix} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} \\right) = \\sigma \\left( " + " + ".join([f"w_{i+1}n_{i+1}" for i in range(hidden_size)]) + " \\right) "
    act_eq = f"act = \\sigma \\left( " + " + ".join([f"w_{i+1}n_{i+1}" for i in range(hidden_size)]) + " \\right) "

    # The full expanded equation
    full_eq = f"act = \\sigma \\left( " + " + ".join([f"w_{i+1}n_{i+1}" for i in range(hidden_size)]) + " \\right) "


    # Count total weights
    total_weights = len(weights_input_hidden) + len(weights_hidden_output)

    # Print results with $$ to ensure LaTeX formatting
    print(f"$$")
    print(f"Win = {win_latex} $$")
    print(f"$$")
    print(f"whid = {whid_latex} $$")
    print(f"$$")
    print(f"x = {x_latex} $$")
    print(f"$$")
    print(f"nhid = {nhid_latex} $$")
    print(f"$$")
    print(f"nout = {nout_latex} $$")
    print(f"$$")
    print(f"nhid = \\sigma(Win \\cdot x) = {nhid_eq} $$")
    print(f"$$")
    print(f"nout = \\sigma(whid \\cdot nhid) = {nout_eq} $$")
    print(f"$$")
    print(f"act = {act_eq} $$")
    print(f"$$")
    print(f"The network has {total_weights} weights.")
    print(f"$$")
    print(f"$$")
    print(f"The full expanded equation is: ")    

# Example usage for structure [2, 4, 1]
structure = [2, 4, 1]
generate_network_latex(structure)


$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x) = \sigma \left( \begin{pmatrix} w_1 & w_2 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} \right) = \begin{pmatrix} \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_1x_1 + w_2x_2) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} \right) = \sigma \left( w_1n_1 + w_2n_2 + w_3n_3 + w_4n_4 \right)  $$
$$
act = act = \sigma \left( w_1n_1 + w_2n_2 + w_3n_3 + w_4n_4 \right)  $$
$$
The network has 12 weights.
$$
$$
The full expanded equation is: act = \sigma \left( w_1n_1 + w_2n_2 

$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x) = \sigma \left( \begin{pmatrix} w_1 & w_2 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} \right) = \begin{pmatrix} \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_1x_1 + w_2x_2) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} \right) = \sigma \left( w_1n_1 + w_2n_2 + w_3n_3 + w_4n_4 \right)  $$
$$
act = act = \sigma \left( w_1n_1 + w_2n_2 + w_3n_3 + w_4n_4 \right)  $$

The network has 12 weights.



# Full equation expanded version for the with bias

In [2]:
def generate_network_latex(structure):
    input_size = structure[0]
    hidden_size = structure[1]
    output_size = structure[2]

    # Generate weight matrices
    weights_input_hidden = [f"w_{i+1}" for i in range(input_size * hidden_size)]
    weights_hidden_output = [f"w_{i+1}" for i in range(input_size * hidden_size, input_size * hidden_size + hidden_size * output_size)]

    # Generate variable matrices
    x_vars = [f"x_{i+1}" for i in range(input_size)]
    n_hidden_vars = [f"n_{i+1}" for i in range(hidden_size)]
    n_output_vars = [f"n_{i+1}" for i in range(hidden_size, hidden_size + output_size)]

    # Generate LaTeX strings
    win_latex = f"\\begin{{pmatrix}} " + " & ".join([f"w_{i+1}" for i in range(hidden_size)]) + " \\end{pmatrix} "
    whid_latex = f"\\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} "
    x_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} "
    nhid_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} "
    nout_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_output_vars) + " \\end{pmatrix} "

    # Generate activation function LaTeX
    nhid_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join([f"w_{i+1}" for i in range(input_size)]) + " \\end{pmatrix} \\cdot \\begin{pmatrix} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} \\right) = \\begin{{pmatrix}} " + " \\\\ ".join([f"\\sigma(" + " + ".join([f"{weights_input_hidden[input_size*j + i]}{x_vars[i]}" for i in range(input_size)]) + ")" for j in range(hidden_size)]) + " \\end{pmatrix} "
    nout_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} \\cdot \\begin{{pmatrix}} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} \\right) = \\sigma \\left( " + " + ".join([f"{weights_hidden_output[j]}{n_hidden_vars[j]}" for j in range(hidden_size)]) + " \\right) "

    # The full expanded equation
    expanded_terms = []
    for j in range(hidden_size):
        hidden_expanded = " + ".join([f"{weights_input_hidden[input_size*j + i]}{x_vars[i]}" for i in range(input_size)])
        expanded_terms.append(f"{weights_hidden_output[j]} \\cdot \\sigma({hidden_expanded})")

    full_eq = f"act = \\sigma \\left( " + " + ".join(expanded_terms) + " \\right)"

    # Count total weights
    total_weights = len(weights_input_hidden) + len(weights_hidden_output)

    # Print results with $$ to ensure LaTeX formatting
    print(f"$$")
    print(f"Win = {win_latex} $$")
    print(f"$$")
    print(f"whid = {whid_latex} $$")
    print(f"$$")
    print(f"x = {x_latex} $$")
    print(f"$$")
    print(f"nhid = {nhid_latex} $$")
    print(f"$$")
    print(f"nout = {nout_latex} $$")
    print(f"$$")
    print(f"nhid = \\sigma(Win \\cdot x) = {nhid_eq} $$")
    print(f"$$")
    print(f"nout = \\sigma(whid \\cdot nhid) = {nout_eq} $$")
    print(f"$$")
    print(f"act = {full_eq} $$")
    print(f"$$")
    print(f"The network has {total_weights} weights.")
    print(f"$$")

# Example usage for structure [2, 4, 1]
structure = [2, 4, 1]
generate_network_latex(structure)


$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x) = \sigma \left( \begin{pmatrix} w_1 & w_2 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} \right) = \begin{{pmatrix}} \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_3x_1 + w_4x_2) \\ \sigma(w_5x_1 + w_6x_2) \\ \sigma(w_7x_1 + w_8x_2) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{{pmatrix}} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} \right) = \sigma \left( w_9n_1 + w_10n_2 + w_11n_3 + w_12n_4 \right)  $$
$$
act = act = \sigma \left( w_9 \cdot \sigma(w_1x_1 + w_2x_2) + w_10 \cdot \sigma(w_3x_1 + w_4x_2) + w_11 \cdot \sigma(w_5x_1 + w_6x_2) + w_12 \cdot \sigma(w_7x_1 + w_8x_2

$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x) = \sigma \left( \begin{pmatrix} w_1 & w_2 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} \right) = \begin{pmatrix} \sigma(w_1x_1 + w_2x_2) \\ \sigma(w_3x_1 + w_4x_2) \\ \sigma(w_5x_1 + w_6x_2) \\ \sigma(w_7x_1 + w_8x_2) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} \right) = \sigma \left( w_9n_1 + w_10n_2 + w_11n_3 + w_12n_4 \right)  $$
$$
act = act = \sigma \left( w_9 \cdot \sigma(w_1x_1 + w_2x_2) + w_10 \cdot \sigma(w_3x_1 + w_4x_2) + w_11 \cdot \sigma(w_5x_1 + w_6x_2) + w_12 \cdot \sigma(w_7x_1 + w_8x_2) \right) $$

The network has 12 weights.



# Full equation of a network with any structure so i can have the Latex code: with bias

In [18]:
def generate_network_latex_with_recurrent(structure):
    input_size = structure[0]
    hidden_size = structure[1]
    output_size = structure[2]

    # Generate weight matrices
    weights_input_hidden = [f"w_{i+1}" for i in range(input_size * hidden_size)]
    weights_hidden_output = [f"w_{i+1}" for i in range(input_size * hidden_size, input_size * hidden_size + hidden_size * output_size)]

    # Generate variable matrices
    x_vars = [f"x_{i+1}" for i in range(input_size)]
    n_hidden_vars = [f"n_{i+1}" for i in range(hidden_size)]
    n_output_vars = [f"n_{i+1}" for i in range(hidden_size, hidden_size + output_size)]

    # Generate bias terms
    biases_hidden = [f"b_{i+1}" for i in range(hidden_size)]
    biases_output = [f"b_{i+1+hidden_size}" for i in range(output_size)]

    # Generate LaTeX strings
    win_latex = f"\\begin{{pmatrix}} " + " & ".join(weights_input_hidden) + " \\end{pmatrix} "
    whid_latex = f"\\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} "
    x_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} "
    nhid_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} "
    nout_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_output_vars) + " \\end{pmatrix} "

    # Add biases
    bias_hidden_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(biases_hidden) + " \\end{pmatrix} "
    bias_output_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(biases_output) + " \\end{pmatrix} "

    # Generate activation function LaTeX
    nhid_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join(weights_input_hidden) + " \\end{pmatrix} \\cdot \\begin{pmatrix} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} + \\begin{pmatrix} " + " \\\\ ".join(biases_hidden) + " \\end{pmatrix} \\right) = \\begin{pmatrix} " + " \\\\ ".join([f"\\sigma(w_{i+1}x_{i+1} + b_{i+1})" for i in range(hidden_size)]) + " \\end{pmatrix} "
    nout_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} \\cdot \\begin{pmatrix} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} + \\begin{pmatrix} " + " \\\\ ".join(biases_output) + " \\end{pmatrix} \\right) = \\sigma \\left( " + " + ".join([f"w_{i+1}\\sigma(w_{i+1}x_{i+1} + b_{i+1})" for i in range(hidden_size)]) + " \\right) "
    act_eq = f"act = \\sigma \\left( " + " + ".join([f"w_{i+1}\\sigma(w_{i+1}x_{i+1} + b_{i+1})" for i in range(hidden_size)]) + " \\right) "

    # Count total weights
    total_feed_forward_weights = len(weights_input_hidden) + len(weights_hidden_output)
    total_recurrent_weights = hidden_size  # One recurrent connection per hidden neuron
    total_biases = len(biases_hidden) + len(biases_output)
    total_weights = total_feed_forward_weights + total_recurrent_weights + total_biases

    # Print results with $$ to ensure LaTeX formatting
    print(f"$$")
    print(f"Win = {win_latex} $$")
    print(f"$$")
    print(f"whid = {whid_latex} $$")
    print(f"$$")
    print(f"x = {x_latex} $$")
    print(f"$$")
    print(f"nhid = {nhid_latex} $$")
    print(f"$$")
    print(f"nout = {nout_latex} $$")
    print(f"$$")
    print(f"nhid = \\sigma(Win \\cdot x + \\text{{biases}}) = {nhid_eq} $$")
    print(f"$$")
    print(f"nout = \\sigma(whid \\cdot nhid + \\text{{biases}}) = {nout_eq} $$")
    print(f"$$")
    print(f"act = {act_eq} $$")
    print(f"$$")
    print(f"The Feed-Forward Weights: {total_feed_forward_weights} weights.")
    print(f"The Recurrent Connections: {total_recurrent_weights} weights.")
    print(f"Total Biases: {total_biases} weights.")
    print(f"Now, The network has {total_weights} weights.")
    print(f"$$")

# Example usage for structure [2, 4, 1] with biases and recurrent connections
structure = [2, 4, 1]
generate_network_latex_with_recurrent(structure)

$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x + \text{biases}) = \sigma \left( \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} + \begin{pmatrix} b_1 \\ b_2 \\ b_3 \\ b_4 \end{pmatrix} \right) = \begin{pmatrix} \sigma(w_1x_1 + b_1) \\ \sigma(w_2x_2 + b_2) \\ \sigma(w_3x_3 + b_3) \\ \sigma(w_4x_4 + b_4) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid + \text{biases}) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} + \begin{pmatrix} b_5 \end{pmatrix} \right) = \sigma \left( w_1\sigma(w_1x_1 + b_1) + w_2\sigma(w_2x_2 + b_2) + 

$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x + \text{biases}) = \sigma \left( \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} + \begin{pmatrix} b_1 \\ b_2 \\ b_3 \\ b_4 \end{pmatrix} \right) = \begin{pmatrix} \sigma(w_1x_1 + b_1) \\ \sigma(w_2x_2 + b_2) \\ \sigma(w_3x_3 + b_3) \\ \sigma(w_4x_4 + b_4) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid + \text{biases}) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} + \begin{pmatrix} b_5 \end{pmatrix} \right) = \sigma \left( w_1\sigma(w_1x_1 + b_1) + w_2\sigma(w_2x_2 + b_2) + w_3\sigma(w_3x_3 + b_3) + w_4\sigma(w_4x_4 + b_4) \right)  $$
$$
act = act = \sigma \left( w_1\sigma(w_1x_1 + b_1) + w_2\sigma(w_2x_2 + b_2) + w_3\sigma(w_3x_3 + b_3) + w_4\sigma(w_4x_4 + b_4) \right)  $$

**The Feed-Forward Weights**: 12 weights.
**The Recurrent Connections**: 4 weights.
**Total Biases**: 5 weights.
**Now, The network has** 21 weights.



# Second methodology:  priority

In [20]:
def generate_network_latex_with_recurrent(structure):
    input_size = structure[0]
    hidden_size = structure[1]
    output_size = structure[2]

    # Generate weight matrices
    weights_input_hidden = [f"w_{i+1}" for i in range(input_size * hidden_size)]
    weights_hidden_output = [f"w_{i+1}" for i in range(input_size * hidden_size, input_size * hidden_size + hidden_size * output_size)]

    # Generate variable matrices
    x_vars = [f"x_{i+1}" for i in range(input_size)]
    n_hidden_vars = [f"n_{i+1}" for i in range(hidden_size)]
    n_output_vars = [f"n_{i+1}" for i in range(hidden_size, hidden_size + output_size)]

    # Generate bias terms
    biases_hidden = [f"b_{i+1}" for i in range(hidden_size)]
    biases_output = [f"b_{i+1+hidden_size}" for i in range(output_size)]

    # Generate LaTeX strings
    win_latex = f"\\begin{{pmatrix}} " + " & ".join(weights_input_hidden) + " \\end{pmatrix} "
    whid_latex = f"\\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} "
    x_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} "
    nhid_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} "
    nout_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_output_vars) + " \\end{pmatrix} "

    # Add biases
    bias_hidden_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(biases_hidden) + " \\end{pmatrix} "
    bias_output_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(biases_output) + " \\end{pmatrix} "

    # Generate activation function LaTeX
    nhid_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join(weights_input_hidden) + " \\end{pmatrix} \\cdot \\begin{pmatrix} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} + \\begin{pmatrix} " + " \\\\ ".join(biases_hidden) + " \\end{pmatrix} \\right) = \\begin{pmatrix} " + " \\\\ ".join([f"\\sigma(w_{i+1}x_{i+1} + b_{i+1})" for i in range(hidden_size)]) + " \\end{pmatrix} "
    nout_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} \\cdot \\begin{pmatrix} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} + \\begin{pmatrix} " + " \\\\ ".join(biases_output) + " \\end{pmatrix} \\right) = \\sigma \\left( " + " + ".join([f"w_{i+1}\\sigma(w_{i+1}x_{i+1} + b_{i+1})" for i in range(hidden_size)]) + " \\right) "
    act_eq = f"act = \\sigma \\left( " + " + ".join([f"w_{i+1}\\sigma(w_{i+1}x_{i+1} + b_{i+1})" for i in range(hidden_size)]) + " \\right) "

    # Count total weights
    total_feed_forward_weights = len(weights_input_hidden) + len(weights_hidden_output)
    total_recurrent_weights = hidden_size * hidden_size  # Fully connected recurrent connections in hidden layer
    total_biases = len(biases_hidden) + len(biases_output)
    total_weights = total_feed_forward_weights + total_recurrent_weights + total_biases

    # Print results with $$ to ensure LaTeX formatting
    print(f"$$")
    print(f"Win = {win_latex} $$")
    print(f"$$")
    print(f"whid = {whid_latex} $$")
    print(f"$$")
    print(f"x = {x_latex} $$")
    print(f"$$")
    print(f"nhid = {nhid_latex} $$")
    print(f"$$")
    print(f"nout = {nout_latex} $$")
    print(f"$$")
    print(f"nhid = \\sigma(Win \\cdot x + \\text{{biases}}) = {nhid_eq} $$")
    print(f"$$")
    print(f"nout = \\sigma(whid \\cdot nhid + \\text{{biases}}) = {nout_eq} $$")
    print(f"$$")
    print(f"act = {act_eq} $$")
    print(f"$$")
    print(f"The Feed-Forward Weights: {total_feed_forward_weights} weights.")
    print(f"The Recurrent Connections: {total_recurrent_weights} weights.")
    print(f"Total Biases: {total_biases} weights.")
    print(f"Now, The network has {total_weights} weights.")
    print(f"$$")

# Example usage for structure [2, 4, 1] with biases and recurrent connections
structure = [2, 4, 1]
generate_network_latex_with_recurrent(structure)

$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x + \text{biases}) = \sigma \left( \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} + \begin{pmatrix} b_1 \\ b_2 \\ b_3 \\ b_4 \end{pmatrix} \right) = \begin{pmatrix} \sigma(w_1x_1 + b_1) \\ \sigma(w_2x_2 + b_2) \\ \sigma(w_3x_3 + b_3) \\ \sigma(w_4x_4 + b_4) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid + \text{biases}) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} + \begin{pmatrix} b_5 \end{pmatrix} \right) = \sigma \left( w_1\sigma(w_1x_1 + b_1) + w_2\sigma(w_2x_2 + b_2) + 

$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x + \text{biases}) = \sigma \left( \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} + \begin{pmatrix} b_1 \\ b_2 \\ b_3 \\ b_4 \end{pmatrix} \right) = \begin{pmatrix} \sigma(w_1x_1 + b_1) \\ \sigma(w_2x_2 + b_2) \\ \sigma(w_3x_3 + b_3) \\ \sigma(w_4x_4 + b_4) \end{pmatrix}  $$
$$
nout = \sigma(whid \cdot nhid + \text{biases}) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} + \begin{pmatrix} b_5 \end{pmatrix} \right) = \sigma \left( w_1\sigma(w_1x_1 + b_1) + w_2\sigma(w_2x_2 + b_2) + w_3\sigma(w_3x_3 + b_3) + w_4\sigma(w_4x_4 + b_4) \right)  $$
$$
act = act = \sigma \left( w_1\sigma(w_1x_1 + b_1) + w_2\sigma(w_2x_2 + b_2) + w_3\sigma(w_3x_3 + b_3) + w_4\sigma(w_4x_4 + b_4) \right)  $$

**The Feed-Forward Weights**: 12 weights.
**The Recurrent Connections**: 16 weights.
**Total Biases**: 5 weights.
**Now, The network has 33 weights.**



# With Bias and Recurrent Connections with a fully expanded equation

In [3]:
def generate_network_latex_with_recurrent(structure):
    input_size = structure[0]
    hidden_size = structure[1]
    output_size = structure[2]

    # Generate weight matrices
    weights_input_hidden = [f"w_{i+1}" for i in range(input_size * hidden_size)]
    weights_hidden_output = [f"w_{i+1}" for i in range(input_size * hidden_size, input_size * hidden_size + hidden_size * output_size)]
    weights_hidden_hidden = [f"u_{i+1}" for i in range(hidden_size * hidden_size)]  # Recurrent weights

    # Generate variable matrices
    x_vars = [f"x_{i+1}" for i in range(input_size)]
    n_hidden_vars = [f"n_{i+1}" for i in range(hidden_size)]
    n_output_vars = [f"n_{i+1}" for i in range(hidden_size, hidden_size + output_size)]

    # Generate bias terms
    biases_hidden = [f"b_{i+1}" for i in range(hidden_size)]
    biases_output = [f"b_{i+1+hidden_size}" for i in range(output_size)]

    # Generate LaTeX strings
    win_latex = f"\\begin{{pmatrix}} " + " & ".join(weights_input_hidden) + " \\end{pmatrix} "
    whid_latex = f"\\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} "
    x_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} "
    nhid_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} "
    nout_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(n_output_vars) + " \\end{pmatrix} "

    # Add biases
    bias_hidden_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(biases_hidden) + " \\end{pmatrix} "
    bias_output_latex = f"\\begin{{pmatrix}} " + " \\\\ ".join(biases_output) + " \\end{pmatrix} "

    # Generate activation function LaTeX for hidden layer with recurrent connections
    nhid_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join(weights_input_hidden) + " \\end{pmatrix} \\cdot \\begin{{pmatrix}} " + " \\\\ ".join(x_vars) + " \\end{pmatrix} + \\begin{{pmatrix}} " + " & ".join(weights_hidden_hidden) + " \\end{pmatrix} \\cdot \\begin{{pmatrix}} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} + \\begin{{pmatrix}} " + " \\\\ ".join(biases_hidden) + " \\end{pmatrix} \\right)"

    # Generate activation function LaTeX for output layer
    nout_eq = f"\\sigma \\left( \\begin{{pmatrix}} " + " & ".join(weights_hidden_output) + " \\end{pmatrix} \\cdot \\begin{{pmatrix}} " + " \\\\ ".join(n_hidden_vars) + " \\end{pmatrix} + \\begin{{pmatrix}} " + " \\\\ ".join(biases_output) + " \\end{pmatrix} \\right)"

    # Full expanded equation
    expanded_terms = []
    for j in range(hidden_size):
        hidden_expanded = " + ".join([f"{weights_input_hidden[input_size*j + i]}{x_vars[i]}" for i in range(input_size)])
        recurrent_expanded = " + ".join([f"{weights_hidden_hidden[hidden_size*j + i]}{n_hidden_vars[i]}" for i in range(hidden_size)])
        expanded_terms.append(f"{weights_hidden_output[j]} \\cdot \\sigma({hidden_expanded} + {recurrent_expanded} + {biases_hidden[j]})")

    full_eq = f"act = \\sigma \\left( " + " + ".join(expanded_terms) + " + " + " + ".join(biases_output) + " \\right)"

    # Count total weights
    total_feed_forward_weights = len(weights_input_hidden) + len(weights_hidden_output)
    total_recurrent_weights = hidden_size * hidden_size  # Fully connected recurrent connections in hidden layer
    total_biases = len(biases_hidden) + len(biases_output)
    total_weights = total_feed_forward_weights + total_recurrent_weights + total_biases

    # Print results with $$ to ensure LaTeX formatting
    print(f"$$")
    print(f"Win = {win_latex} $$")
    print(f"$$")
    print(f"whid = {whid_latex} $$")
    print(f"$$")
    print(f"x = {x_latex} $$")
    print(f"$$")
    print(f"nhid = {nhid_latex} $$")
    print(f"$$")
    print(f"nout = {nout_latex} $$")
    print(f"$$")
    print(f"nhid = \\sigma(Win \\cdot x + U \\cdot nhid + \\text{{biases}}) = {nhid_eq} $$")
    print(f"$$")
    print(f"nout = \\sigma(whid \\cdot nhid + \\text{{biases}}) = {nout_eq} $$")
    print(f"$$")
    print(f"act = {full_eq} $$")
    print(f"$$")
    print(f"The Feed-Forward Weights: {total_feed_forward_weights} weights.")
    print(f"The Recurrent Connections: {total_recurrent_weights} weights.")
    print(f"Total Biases: {total_biases} weights.")
    print(f"Now, The network has {total_weights} weights.")
    print(f"$$")

# Example usage for structure [2, 4, 1] with biases and recurrent connections
structure = [2, 4, 1]
generate_network_latex_with_recurrent(structure)


$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x + U \cdot nhid + \text{biases}) = \sigma \left( \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix} \cdot \begin{{pmatrix}} x_1 \\ x_2 \end{pmatrix} + \begin{{pmatrix}} u_1 & u_2 & u_3 & u_4 & u_5 & u_6 & u_7 & u_8 & u_9 & u_10 & u_11 & u_12 & u_13 & u_14 & u_15 & u_16 \end{pmatrix} \cdot \begin{{pmatrix}} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} + \begin{{pmatrix}} b_1 \\ b_2 \\ b_3 \\ b_4 \end{pmatrix} \right) $$
$$
nout = \sigma(whid \cdot nhid + \text{biases}) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{{pmatrix}} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} + \begin{{pmatrix}}

$$
Win = \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix}  $$
$$
whid = \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix}  $$
$$
x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}  $$
$$
nhid = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix}  $$
$$
nout = \begin{pmatrix} n_5 \end{pmatrix}  $$
$$
nhid = \sigma(Win \cdot x + U \cdot nhid + \text{biases}) = \sigma \left( \begin{pmatrix} w_1 & w_2 & w_3 & w_4 & w_5 & w_6 & w_7 & w_8 \end{pmatrix} \cdot \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} + \begin{pmatrix} u_1 & u_2 & u_3 & u_4 & u_5 & u_6 & u_7 & u_8 & u_9 & u_10 & u_11 & u_12 & u_13 & u_14 & u_15 & u_16 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} + \begin{pmatrix} b_1 \\ b_2 \\ b_3 \\ b_4 \end{pmatrix} \right) $$
$$
nout = \sigma(whid \cdot nhid + \text{biases}) = \sigma \left( \begin{pmatrix} w_9 & w_10 & w_11 & w_12 \end{pmatrix} \cdot \begin{pmatrix} n_1 \\ n_2 \\ n_3 \\ n_4 \end{pmatrix} + \begin{pmatrix} b_5 \end{pmatrix} \right) $$
$$
act = act = \sigma \left( w_9 \cdot \sigma(w_1x_1 + w_2x_2 + u_1n_1 + u_2n_2 + u_3n_3 + u_4n_4 + b_1) + w_10 \cdot \sigma(w_3x_1 + w_4x_2 + u_5n_1 + u_6n_2 + u_7n_3 + u_8n_4 + b_2) + w_11 \cdot \sigma(w_5x_1 + w_6x_2 + u_9n_1 + u_10n_2 + u_11n_3 + u_12n_4 + b_3) + w_12 \cdot \sigma(w_7x_1 + w_8x_2 + u_13n_1 + u_14n_2 + u_15n_3 + u_16n_4 + b_4) + b_5 \right) $$

The Feed-Forward Weights: 12 weights.
The Recurrent Connections: 16 weights.
Total Biases: 5 weights.
Now, The network has 33 weights.

